FROM ubuntu:latest

LABEL name="abisolaazeezat"

ARG T_VERSION='1.6.6'
ARG P_VERSION='1.8.0'

# Install dependencies
RUN apt update && apt install -y curl jq net-tools wget unzip \
    && apt install -y nginx iputils-ping


EXPOSE 80
# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
